/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppForm: typeof import('./src/components/AppForm.vue')['default']
    AppPagination: typeof import('./src/components/AppPagination.vue')['default']
    AppPopover: typeof import('./src/components/AppPopover.vue')['default']
    ElseForm: typeof import('./src/views/design/nodeFormOption/ifs/else/elseForm.vue')['default']
    ElseInput: typeof import('./src/views/design/nodeFormOption/ifs/else/elseInput.vue')['default']
    EndIfForm: typeof import('./src/views/design/nodeFormOption/endIfForm.vue')['default']
    EndIfInput: typeof import('./src/views/design/nodeFormOption/ifs/endIf/endIfInput.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IfForm: typeof import('./src/views/design/nodeFormOption/ifForm.vue')['default']
    IfInput: typeof import('./src/views/design/nodeFormOption/ifs/if/ifInput.vue')['default']
    Inputs: typeof import('./src/views/design/nodeFormOption/ifs/if/inputs.vue')['default']
    LogOut: typeof import('./src/components/LogOut.vue')['default']
    OpenPageInput: typeof import('./src/views/design/nodeFormOption/webPage/openPage/openPageInput.vue')['default']
    Print: typeof import('./src/views/design/nodeFormOption/others/print/print.vue')['default']
    PrintInput: typeof import('./src/views/design/nodeFormOption/others/print/printInput.vue')['default']
    RandomNum: typeof import('./src/views/design/nodeFormOption/others/random/randomNum.vue/randomNum.vue')['default']
    RandomNumInput: typeof import('./src/views/design/nodeFormOption/others/random/randomNumInput.vue')['default']
    RandomNumOutput: typeof import('./src/views/design/nodeFormOption/others/random/randomNumOutput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/SvgIcon.vue')['default']
    WebpageForm: typeof import('./src/views/design/nodeFormOption/webPage/openPage/webpageForm.vuee/webpageForm.vue')['default']
  }
}
